Check formatting and import order

diff --git a/.github/workflows/go.yaml b/.github/workflows/go.yaml
--- a/.github/workflows/go.yaml
+++ b/.github/workflows/go.yaml
@@ -32,6 +32,18 @@ jobs:
       - uses: actions/setup-go@v5
         with:
           go-version-file: 'go.mod'
+      - run: |
+          make fmt
+          if [[ "$(git status --porcelain | wc -l)" -ne 0 ]]; then
+            echo "::error::Go files are not formatted correctly."
+            exit 1
+          fi
+      - run: |
+          make imports
+          if [[ "$(git status --porcelain | wc -l)" -ne 0 ]]; then
+            echo "::error::Go imports are not formatted correctly."
+            exit 1
+          fi
       - run: make lint
       - run: make test
       - uses: helm/kind-action@v1
