Add deepcopy-gen and validation-gen
Signed-off-by: Nelo-T. Wallus <red.brush9525@fastmail.com>

diff --git a/.github/workflows/go.yaml b/.github/workflows/go.yaml
--- a/.github/workflows/go.yaml
+++ b/.github/workflows/go.yaml
@@ -33,6 +33,12 @@ jobs:
         with:
           go-version-file: 'go.mod'
       - run: |
+          make codegen
+          if [[ "$(git status --porcelain | wc -l)" -ne 0 ]]; then
+            echo "::error::Missing codegen run."
+            exit 1
+          fi
+      - run: |
           make fmt
           if [[ "$(git status --porcelain | wc -l)" -ne 0 ]]; then
             echo "::error::Go files are not formatted correctly."
